export type ScGeoMatch = {
  allowed: boolean;
  city: string | null;
  region: string | null;
  reason: string;
};

const SC_CITIES: Array<{ name: string; region: string; aliases?: string[] }> = [
  { name: 'Joinville', region: 'Norte' },
  { name: 'Florianópolis', region: 'Grande Florianópolis', aliases: ['Florianopolis', 'Floripa'] },
  { name: 'Blumenau', region: 'Vale do Itajaí' },
  { name: 'Itajaí', region: 'Litoral Norte', aliases: ['Itajai'] },
  { name: 'São José', region: 'Grande Florianópolis', aliases: ['Sao Jose'] },
  { name: 'Chapecó', region: 'Oeste', aliases: ['Chapeco'] },
  { name: 'Palhoça', region: 'Grande Florianópolis', aliases: ['Palhoca'] },
  { name: 'Criciúma', region: 'Sul', aliases: ['Criciuma'] },
  { name: 'Jaraguá do Sul', region: 'Norte/Vale do Itapocu', aliases: ['Jaragua do Sul'] },
  { name: 'Lages', region: 'Serra' },
  { name: 'Balneário Camboriú', region: 'Litoral Norte', aliases: ['Balneario Camboriu'] },
  { name: 'Brusque', region: 'Vale do Itajaí' },
  { name: 'Tubarão', region: 'Sul', aliases: ['Tubarao'] },
  { name: 'Camboriú', region: 'Litoral Norte', aliases: ['Camboriu'] },
  { name: 'São Bento do Sul', region: 'Norte', aliases: ['Sao Bento do Sul'] },
  { name: 'Caçador', region: 'Meio-Oeste', aliases: ['Cacador'] },
  { name: 'Concórdia', region: 'Oeste', aliases: ['Concordia'] },
  { name: 'Navegantes', region: 'Litoral Norte' },
  { name: 'Rio do Sul', region: 'Alto Vale' },
  { name: 'Araranguá', region: 'Sul', aliases: ['Ararangua'] },
  { name: 'Gaspar', region: 'Vale do Itajaí' },
  { name: 'Biguaçu', region: 'Grande Florianópolis', aliases: ['Biguacu'] },
  { name: 'Indaial', region: 'Vale do Itajaí' },
  { name: 'Mafra', region: 'Planalto Norte' },
  { name: 'Canoinhas', region: 'Planalto Norte' },
  { name: 'Joaçaba', region: 'Meio-Oeste', aliases: ['Joacaba'] },
  { name: 'Xanxerê', region: 'Oeste', aliases: ['Xanxere'] },
  { name: 'Videira', region: 'Meio-Oeste' },
  { name: 'Fraiburgo', region: 'Meio-Oeste' },
  { name: 'São Miguel do Oeste', region: 'Oeste', aliases: ['Sao Miguel do Oeste'] },
  { name: 'Porto União', region: 'Planalto Norte', aliases: ['Porto Uniao'] },
  { name: 'Içara', region: 'Sul', aliases: ['Icara'] },
  { name: 'Laguna', region: 'Sul' },
  { name: 'Imbituba', region: 'Sul' },
  { name: 'Penha', region: 'Litoral Norte' },
  { name: 'Porto Belo', region: 'Litoral Norte' },
  { name: 'Itapema', region: 'Litoral Norte' },
  { name: 'Tijucas', region: 'Grande Florianópolis' },
  { name: 'Xaxim', region: 'Oeste' },
  { name: 'Seara', region: 'Oeste' },
  { name: 'Maravilha', region: 'Oeste' },
  { name: 'Pinhalzinho', region: 'Oeste' },
  { name: 'Abelardo Luz', region: 'Oeste' },
  { name: 'São Lourenço do Oeste', region: 'Oeste', aliases: ['Sao Lourenco do Oeste'] },
  { name: 'Dionísio Cerqueira', region: 'Oeste', aliases: ['Dionisio Cerqueira'] },
  { name: 'Curitibanos', region: 'Serra/Meio-Oeste' },
  { name: 'Campos Novos', region: 'Meio-Oeste' },
  { name: 'Herval d’Oeste', region: 'Meio-Oeste', aliases: ['Herval d Oeste', 'Herval do Oeste'] },
  { name: 'Capinzal', region: 'Meio-Oeste' },
  { name: 'Treze Tílias', region: 'Meio-Oeste', aliases: ['Treze Tilias'] },
  { name: 'Guaramirim', region: 'Norte/Vale do Itapocu' },
  { name: 'Schroeder', region: 'Norte/Vale do Itapocu' },
  { name: 'Araquari', region: 'Norte' },
  { name: 'Garuva', region: 'Norte' },
  { name: 'São Francisco do Sul', region: 'Norte', aliases: ['Sao Francisco do Sul'] },
  { name: 'Porto União', region: 'Planalto Norte', aliases: ['Porto Uniao'] },
  { name: 'Três Barras', region: 'Planalto Norte', aliases: ['Tres Barras'] },
  { name: 'Balneário Piçarras', region: 'Litoral Norte', aliases: ['Balneario Picarras'] },
  { name: 'Bombinhas', region: 'Litoral Norte' },
  { name: 'Ilhota', region: 'Vale do Itajaí' },
  { name: 'Pomerode', region: 'Vale do Itajaí' },
  { name: 'Timbó', region: 'Vale do Itajaí', aliases: ['Timbo'] },
  { name: 'Ituporanga', region: 'Alto Vale' },
  { name: 'Taió', region: 'Alto Vale', aliases: ['Taio'] },
  { name: 'Braço do Norte', region: 'Sul', aliases: ['Braco do Norte'] },
  { name: 'Orleans', region: 'Sul' },
  { name: 'Urussanga', region: 'Sul' },
  { name: 'Sombrio', region: 'Sul' },
  { name: 'Balneário Rincão', region: 'Sul', aliases: ['Balneario Rincao'] },
  { name: 'Garopaba', region: 'Sul' },
  { name: 'São Joaquim', region: 'Serra', aliases: ['Sao Joaquim'] },
  { name: 'Urubici', region: 'Serra' },
  { name: 'Otacílio Costa', region: 'Serra', aliases: ['Otacilio Costa'] },
  { name: 'Correia Pinto', region: 'Serra' },
];

const SC_SOURCE_MARKERS = [
  'nsctotal', 'nsc total', 'ndmais', 'scc10', 'clicrdc', 'jornal razao', 'jornal razão', 'omunicipio',
  'o municipio', 'misturebas', 'tn sul', 'sul in foco', 'visor noticias', 'visor notícias',
  'obvsc', 'folha de sc', 'portal via certa', 'portal litoral sul', 'portal meneghetti',
  'portal agora noticias', 'portal agora notícias', 'jornal metas', 'canal ideal', 'g1 sc',
  'g1 santa catarina', 'diarinho', 'imagem da ilha', 'santa catarina em pauta',
  'gazeta sbs', 'rcn online', 'correio sc', 'sc portais', 'tudo aqui sc',
  'blog do prisco', 'donna da noticia', 'donna da notícia', 'donnadanoticia',
  'oeste mais', 'oestemais', 'click xaxim', 'clickxaxim', 'nova fm 103',
  'di regional', 'diregional', 'agencia icem', 'agência icem', 'agenciaicem',
  'nsctotal.com.br', 'diarinho.net', 'imagemdailha.com.br',
  'scc10.com.br', 'santacatarinaempauta.com.br', 'rcnonline.com.br',
  'correiosc.com.br', 'gazetasbs.com.br', 'scportais.com.br',
  'tudoaquisc.com.br', 'blogdoprisco.com.br', 'donnadanoticia.com.br',
  'oestemais.com', 'clickxaxim.com.br', 'novafm103.com.br',
  'diregional.com.br', 'agenciaicem.com.br',
  '4oito',
  '4oito.com.br',
  '89fmjoinville',
  'amanda fm',
  'amanda.fm',
  'araguaia brusque',
  'araguaiabq',
  'atlantidafloripa',
  'atlântida floripa',
  'atual fm',
  'atualfm',
  'band fm tubarão',
  'bandfmtubarao',
  'cacadoronline',
  'cacadoronline.com.br',
  'caçador online',
  'cbn floripa',
  'cbn joinville',
  'cbnfloripa',
  'cbnjoinville',
  'clicrdc.com.br',
  'clube fm chapecó',
  'clubefm.chapeco',
  'correio lageano',
  'correiolageano',
  'correiolageano.com.br',
  'diariodoiguacu',
  'diariodoiguacu.com.br',
  'diariodosul',
  'diariodosul.com.br',
  'diplomata fm',
  'diplomatafm',
  'diário do alto vale / correio lageano',
  'diário do iguaçu',
  'diário do sul',
  'engeplus.com.br',
  'gcd notícias / vale notícias',
  'hc notícias',
  'hcnoticias',
  'hcnoticias.com.br',
  'imagemdailha',
  'informe bnu',
  'informeblumenau',
  'itajaidigital.com.br',
  'itajaí digital',
  'jornaldiarinho',
  'jovem pan floripa',
  'jovem pan joinville',
  'jovem pan news floripa',
  'jovem pan tubarão',
  'jovempanfloripa',
  'jovempanjoinville',
  'jovempannewsfloripa',
  'jpnewstubarao',
  'lages online',
  'lagesonline',
  'lagesonline.com.br',
  'massa fm blumenau',
  'massa fm chapecó',
  'massa fm concórdia',
  'massa fm criciúma',
  'massa fm lages',
  'massa fm litoral',
  'massa fm rio do sul',
  'massaconcordia101',
  'massafmblumenau',
  'massafmchapeco',
  'massafmcriciuma',
  'massafmlages',
  'massafmlitoral',
  'massafmriodosul',
  'meninafmblu',
  'meninalages',
  'mesorregional',
  'nd mais',
  'nd mais / ndtv',
  'ndmais.com.br',
  'ndtv blumenau',
  'ndtv criciúma',
  'ndtv floripa',
  'ndtv itajaí',
  'ndtv joinville',
  'ndtv lages',
  'ndtv meio-oeste',
  'ndtv oeste',
  'ndtvblumenau',
  'ndtvcriciuma',
  'ndtvfloripa',
  'ndtvitajai',
  'ndtvjoinville',
  'ndtvlages',
  'ndtvmeiooeste',
  'ndtvoeste',
  'noticiahoje',
  'noticiahoje.com.br',
  'noticianoato',
  'noticianoato.com.br',
  'notisul',
  'notisul.com.br',
  'notícia hoje',
  'notícia no ato',
  'nsc tv oficial',
  'nsctvoficial',
  'o diário',
  'o município',
  'o município brusque',
  'odiario.net',
  'odiarionet',
  'oeste capital fm',
  'olhar do vale',
  'olhardovale.com.br',
  'omunicipio.com.br',
  'omunicipiobrusque',
  'ponto norte joinville',
  'pontonortejoinville',
  'portal concórdia',
  'portal da cidade brusque',
  'portal da cidade concórdia',
  'portal engeplus',
  'portal rbv',
  'portalconcordia',
  'portalconcordia.com.br',
  'portaldacidadebrusque',
  'portalengeplus',
  'portallitoralsul',
  'portallitoralsul.com.br',
  'portalolhardovale',
  'portalrbv',
  'portalrbv.com.br',
  'radio92fmcacador',
  'radio_alianca',
  'radiocacanjure',
  'radiochapeco',
  'radiocidadebrusque',
  'radioclubelages',
  'radioconceicaofm',
  'radioeldoradocriciuma',
  'radiomiradoroficial',
  'radiooestecapitalfm',
  'radioruralconcordia',
  'radiosommaior',
  'radiotuba',
  'radiounidavi',
  'radiovideira',
  'record news sc',
  'recordnews_sc',
  'rádio 89fm joinville',
  'rádio 92 fm caçador',
  'rádio aliança',
  'rádio caçanjurê',
  'rádio chapecó',
  'rádio cidade brusque',
  'rádio clube lages',
  'rádio conceição fm',
  'rádio eldorado criciúma',
  'rádio menina blumenau',
  'rádio menina lages',
  'rádio mirador',
  'rádio rural concórdia',
  'rádio tubá',
  'rádio videira',
  'scc sbt',
  'scc10 / scc sbt',
  'sccsbt',
  'som maior',
  'transamericabalneariocamboriu',
  'transamérica balneário camboriú',
  'tv concórdia',
  'tv galega',
  'tvbe joinville',
  'tvbejlleoficial',
  'tvconcordia',
  'tvgalega.oficial',
  'uniaofm965',
  'unidavi fm',
  'unitv',
  'univali fm',
  'univalifm',
  'união fm 96.5',
  'vale.noticias',
  'Blog do Jaime',
  'instagram.com/blogdojaime_blumenau',
  'blogdojaime_blumenau',
  'Blumenau Mil Grau',
  'instagram.com/blumilgrau',
  'blumilgrau',
  'Mesorregional',
  'instagram.com/mesorregional',
  'Cristian Mohr',
  'instagram.com/cristianmohr',
  'cristianmohr',
  'Brusque Mil Grau',
  'instagram.com/bqmilgrau',
  'bqmilgrau',
  'Brusque Zoeira',
  'instagram.com/brusque_zoeira',
  'brusque_zoeira',
  'Brusque Notícias',
  'instagram.com/brusquenoticias',
  'brusquenoticias',
  'O Município Brusque',
  'instagram.com/omunicipiobrusque',
  'omunicipiobrusque',
  'Danilo Visconti',
  'instagram.com/daniloviscontioficial',
  'daniloviscontioficial',
  'Cacá Tavares SC',
  'instagram.com/cacatavaressc',
  'cacatavaressc',
  'Chapecó Online',
  'instagram.com/chapeco.online',
  'chapeco.online',
  'De Chapecó',
  'instagram.com/dechapeco',
  'dechapeco',
  'Chapecó Mil Grau',
  'instagram.com/chapecomilgrauoficial',
  'chapecomilgrauoficial',
  'Criciúma Mil Grau',
  'instagram.com/criciumamilgrau_',
  'criciumamilgrau_',
  'Carvoeiro Doente',
  'instagram.com/carvoeirodoente',
  'carvoeirodoente',
  'Criciúma Notícias',
  'instagram.com/criciumanoticias',
  'criciumanoticias',
  'Elida Feltrin',
  'instagram.com/elidafeltrin',
  'elidafeltrin',
  'Floripa Mil Grau',
  'instagram.com/floripamilgrau',
  'floripamilgrau',
  'Floripa 24h',
  'instagram.com/floripa24h',
  'floripa24h',
  'Dona Bilica',
  'instagram.com/donabilica',
  'donabilica',
  'Itajaí Mil Grau',
  'instagram.com/itaja1m1lgr4u',
  'itaja1m1lgr4u',
  'Itajaí News',
  'instagram.com/itajai.news',
  'itajai.news',
  'Larissa Vanzuita',
  'instagram.com/larissavanzuita',
  'larissavanzuita',
  'Sandro Garcia',
  'instagram.com/sandrogarciaofc',
  'sandrogarciaofc',
  'Joinville Informações',
  'instagram.com/joinvilleinformacoes',
  'joinvilleinformacoes',
  'Joinville Mil Grau',
  'instagram.com/joinville.milgrau',
  'joinville.milgrau',
  'Aconteceu em Joinville',
  'instagram.com/aconteceuemjoinville',
  'aconteceuemjoinville',
  'Joinville Alerta',
  'instagram.com/joinville.alerta',
  'joinville.alerta',
  'Eeeguaaa',
  'instagram.com/eeeguaaa',
  'Larissa D Souza',
  'instagram.com/larissadssouza_',
  'larissadssouza_',
  'Joinville News',
  'instagram.com/joinvillenewsoficial',
  'joinvillenewsoficial',
  'Rio do Sul Mil Grau',
  'instagram.com/riodosulmilgrau',
  'riodosulmilgrau',
  'Tubarão Notícias',
  'instagram.com/tubaraonoticias',
  'tubaraonoticias',
  'Francine Vieira',
  'instagram.com/francinevieira',
  'francinevieira',
  'Lages Mil Grau',
  'instagram.com/lages_milgrau',
  'lages_milgrau',
  'Biguá Tá On',
  'instagram.com/biguataon',
  'biguataon',
  'Lages Online',
  'instagram.com/lagesonline',
  'lagesonline',
  'Amo Lages',
  'instagram.com/amolages',
  'amolages',
  'Viver Lages',
  'instagram.com/viverlages',
  'viverlages',
  'Calebe Costa',
  'instagram.com/calebecostaa',
  'calebecostaa',
  'Concórdia no Grau',
  'instagram.com/concordianograu.oficial',
  'concordianograu.oficial',
  'Concórdia News',
  'instagram.com/concordianews.sc',
  'concordianews.sc',
  'Viver Concórdia',
  'instagram.com/viverconcordia',
  'viverconcordia',
  'Amo Concórdia',
  'instagram.com/amoconcordia',
  'amoconcordia',
  'Cadu de Concórdia',
  'instagram.com/cadudeconcordia',
  'cadudeconcordia',
  'Caçador Mil Graus',
  'instagram.com/cacador_milgraus',
  'cacador_milgraus',
  'Caçador Urgente',
  'instagram.com/cacadorurgente',
  'cacadorurgente',
  'Viver Caçador',
  'instagram.com/vivercacador',
  'vivercacador',
  'Amo Caçador',
  'instagram.com/amocacador',
  'amocacador',
  'Gabriel Malheiro',
  'instagram.com/gabrielmalheiroof',
  'gabrielmalheiroof',
  'Cristian Mohr Facebook',
  'facebook.com/cristianmohr03',
  'Cacá do Berro Facebook',
  'facebook.com/cacadoberro',
  'Floripa 24h Facebook',
  'facebook.com/Florianopolis24h',
  'Mesorregional Facebook',
  'facebook.com/Mesorregional',
  'Brusque Mil Grau Facebook',
  'facebook.com/bqmilgrau',
  'O Município Brusque Facebook',
  'facebook.com/omunicipiobrusque',
  'Portal Engeplus Facebook',
  'facebook.com/portalengeplus',
  'Floripa Mil Grau Grupo',
  'facebook.com/groups/floripamilgraugrupo',
  'Vale do Itajaí Notícias Grupo',
  'facebook.com/groups/1695750343936044',
  'DIARINHO Facebook',
  'facebook.com/jornaldiarinho',
  'Joinville Informações Grupo',
  'facebook.com/groups/850943675296626',
  'Aconteceu em Joinville Grupo',
  'facebook.com/groups/aconteceuemjoinville',
  'Ponto Norte Joinville Grupo',
  'facebook.com/groups/omunicipiojoinville',
  'Joinville de Sempre Grupo',
  'facebook.com/groups/joinvilledeontemjjojedesempre',
  'Rádio Amanda FM Facebook',
  'facebook.com/radioamandafm',
  'Rádio Mirador Facebook',
  'facebook.com/Mirador98.5fm',
  'Notisul Facebook',
  'facebook.com/notisul',
  'Rádio Tubá Facebook',
  'facebook.com/radiotubatb',
  'Lages Mil Grau Grupo',
  'facebook.com/groups/lagesmilgrau',
  'Lages é a minha paixão Grupo',
  'facebook.com/groups/381175958582755',
  'Lages - A Capital das Aldeias Grupo',
  'facebook.com/groups/557086807701611',
  'Doação Lages Grupo',
  'facebook.com/groups/doacaolages',
  'Brechó Não é da Vovó Lages Grupo',
  'facebook.com/groups/brecholages',
  'Bairro Guarujá Lages Grupo',
  'facebook.com/groups/1574033596226283',
  'Moradores do Bairro Coral Grupo',
  'facebook.com/groups/bairrocora',
  'Bairro Habitação Lages Grupo',
  'facebook.com/groups/bairrohabitacao',
  'Moradores de Concórdia 2.0 Grupo',
  'facebook.com/groups/658790629015157',
  'Concórdia Mil Grau Grupo',
  'facebook.com/groups/concordiamilgrau',
  'Atual FM Facebook',
  'facebook.com/atualfm',
  'Rádio Rural Facebook',
  'facebook.com/radioruralfm93.7',
  'Moradores Bairro Nações Concórdia Grupo',
  'facebook.com/groups/bairronacoesconcordia',
  'Bairro Guilherme Reich Grupo',
  'facebook.com/groups/guilhermereich',
  'Moradores do Bairro Imperial Grupo',
  'facebook.com/groups/bairroimperial',
  'Moradores de Caçador SC Grupo',
  'facebook.com/groups/488859477800360',
  'Caçador Antigamente Grupo',
  'facebook.com/groups/AntigoCacador',
  'Caçador Mil Grau Grupo',
  'facebook.com/groups/61577915532060',
  'Portal Notícia Hoje Facebook',
  'facebook.com/noticiahoje',
  'Bairro Martello Caçador Grupo',
  'facebook.com/groups/bairromartello',
  'Moradores do Bairro Berger Grupo',
  'facebook.com/groups/bairroberger',
  'Amigos do Bairro Mutirão Grupo',
  'facebook.com/groups/bairromutirao',
];

const SC_MARKERS = [
  'santa catarina', 'catarinense', 'catarinenses', 'govsc', 'alesc', 'tjsc', 'mpsc', 'tce-sc',
  'pm-sc', 'pmsc', 'pcsc', 'bombeiros de sc', 'defesa civil sc', 'oeste catarinense',
  'sul catarinense', 'norte catarinense', 'vale do itajai', 'vale do itajaí', 'grande florianopolis',
  'grande florianópolis', 'serra catarinense', 'litoral norte', 'litoral sul',
];

const OTHER_STATE_MARKERS = [
  'ceara', 'ceará', 'sul do ceara', 'sul do ceará', 'fortaleza', 'sobral', 'juazeiro do norte',
  'sao paulo', 'são paulo', 'rio de janeiro', 'minas gerais', 'parana', 'paraná', 'rio grande do sul',
  'bahia', 'pernambuco', 'goias', 'goiás', 'mato grosso', 'mato grosso do sul', 'paraiba', 'paraíba',
  'rio grande do norte', 'alagoas', 'sergipe', 'piaui', 'piauí', 'maranhao', 'maranhão', 'amazonas',
  'para ', 'pará', 'acre', 'rondonia', 'rondônia', 'roraima', 'amapa', 'amapá', 'tocantins',
  'espirito santo', 'espírito santo', 'distrito federal', 'brasilia', 'brasília',
];

const REGION_PATTERNS: Array<{ region: string; patterns: string[] }> = [
  { region: 'Oeste', patterns: ['oeste de santa catarina', 'oeste catarinense', 'no oeste', 'regiao oeste', 'região oeste', 'sc 155', 'sc-155'] },
  { region: 'Meio-Oeste', patterns: ['meio oeste', 'meio-oeste', 'meio oeste catarinense', 'meio-oeste catarinense'] },
  { region: 'Sul', patterns: ['sul de santa catarina', 'sul catarinense', 'regiao sul de sc', 'região sul de sc'] },
  { region: 'Norte', patterns: ['norte de santa catarina', 'norte catarinense', 'planalto norte'] },
  { region: 'Vale do Itajaí', patterns: ['vale do itajai', 'vale do itajaí', 'alto vale'] },
  { region: 'Litoral Norte', patterns: ['litoral norte', 'foz do itajai', 'foz do itajaí'] },
  { region: 'Grande Florianópolis', patterns: ['grande florianopolis', 'grande florianópolis'] },
  { region: 'Serra', patterns: ['serra catarinense', 'planalto serrano'] },
];

const SC_ROAD_REGEX = /\b(sc[-\s]?\d{2,3}|br[-\s]?(101|282|470|280|116|153|163|158|285))\b/i;
const OUT_OF_STATE_GOV_DOMAIN = /(^|\.)(ac|al|am|ap|ba|ce|df|es|go|ma|mg|ms|mt|pa|pb|pe|pi|pr|rj|rn|ro|rr|rs|se|sp|to)\.gov\.br$/i;

function normalize(input: string) {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s.-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function containsPhrase(text: string, phrase: string) {
  const normalizedPhrase = normalize(phrase);
  return text.includes(normalizedPhrase);
}

function detectCity(rawText: string) {
  const text = normalize(rawText);
  for (const city of SC_CITIES) {
    const names = [city.name, ...(city.aliases ?? [])];
    if (names.some((name) => containsPhrase(text, name))) return city;
  }
  return null;
}

function detectRegion(rawText: string) {
  const text = normalize(rawText);
  for (const region of REGION_PATTERNS) {
    if (region.patterns.some((pattern) => containsPhrase(text, pattern))) return region.region;
  }
  return null;
}

function hasScMarker(rawText: string) {
  const text = normalize(rawText);
  return SC_MARKERS.some((marker) => containsPhrase(text, marker)) || SC_ROAD_REGEX.test(rawText);
}

function hasScSource(rawText: string) {
  const text = normalize(rawText);
  return SC_SOURCE_MARKERS.some((marker) => containsPhrase(text, marker));
}

function hasOtherStateMarker(rawText: string) {
  const text = normalize(rawText);
  return OTHER_STATE_MARKERS.some((marker) => containsPhrase(text, marker));
}

export function isOutOfStateGovDomain(domain?: string | null) {
  if (!domain) return false;
  return OUT_OF_STATE_GOV_DOMAIN.test(domain.toLowerCase().replace(/^www\./, ''));
}

export function classifySantaCatarinaNews(input: {
  title: string;
  summary?: string | null;
  sourceName?: string | null;
  sourceDomain?: string | null;
  queryCity?: string | null;
  queryRegion?: string | null;
}): ScGeoMatch {
  const fullText = `${input.title} ${input.summary ?? ''} ${input.sourceName ?? ''} ${input.sourceDomain ?? ''}`;
  const cityMatch = detectCity(fullText);
  const regionMatch = detectRegion(fullText);
  const sourceLooksSc = hasScSource(fullText);
  const scMarker = hasScMarker(fullText);
  const otherState = hasOtherStateMarker(fullText) || isOutOfStateGovDomain(input.sourceDomain);
  const queryCityAppears = input.queryCity ? containsPhrase(fullText, input.queryCity) : false;

  if (otherState && !cityMatch && !regionMatch && !scMarker && !sourceLooksSc) {
    return { allowed: false, city: null, region: null, reason: 'fora_de_sc' };
  }

  if (cityMatch) return { allowed: true, city: cityMatch.name, region: cityMatch.region, reason: 'cidade_sc' };
  if (regionMatch) return { allowed: true, city: null, region: regionMatch, reason: 'regiao_sc' };
  if (scMarker) return { allowed: true, city: null, region: input.queryRegion ?? 'SC', reason: 'marcador_sc' };
  if (sourceLooksSc) return { allowed: true, city: input.queryCity ?? null, region: input.queryRegion ?? 'SC', reason: 'fonte_sc' };
  if (queryCityAppears) return { allowed: true, city: input.queryCity ?? null, region: input.queryRegion ?? null, reason: 'cidade_da_busca' };

  return { allowed: false, city: null, region: null, reason: 'sem_contexto_sc' };
}

export function inferScCityAndRegion(input: {
  title: string;
  summary?: string | null;
  sourceName?: string | null;
  sourceDomain?: string | null;
  queryCity?: string | null;
  queryRegion?: string | null;
}) {
  return classifySantaCatarinaNews(input);
}

export const CITY_FILTERS = ['Joinville', 'Florianópolis', 'Blumenau', 'Itajaí', 'Chapecó', 'Criciúma', 'Lages', 'Balneário Camboriú', 'Brusque', 'São José', 'Palhoça', 'Jaraguá do Sul', 'Xanxerê', 'Concórdia', 'São Miguel do Oeste', 'Rio do Sul'];
